use crate::signal::types::SignalId;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::path::PathBuf;

/// A system-level operation the agent can execute.
/// These are real operations — file I/O, shell commands, compilation.
/// All are gated by the continuity check in the executor.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum SystemOp {
    /// Read a file — feeds content hash and size as signal deltas
    ReadFile { path: PathBuf },
    /// Generate and write a new action definition to actions.json
    GenAction,
    /// Generate and apply a source code patch to a target file
    GenSourcePatch { target: SourceTarget },
    /// Execute a whitelisted shell command
    ShellExec { cmd: ShellCmd },
    /// Run cargo build in the workspace
    CargoBuild,
    /// Reload actions.json into the live action space
    ReloadActions,
    /// Write self_prompt.md — the agent's self-description
    WritePrompt,
    /// Read self_prompt.md back (used to verify what was written)
    ReadPrompt,
    /// Checkpoint current state then exec into new binary
    ApplyAndRestart,
    /// Adjust gene's own process nice value (-20 = highest priority, 19 = lowest)
    Renice { niceness: i32 },
    /// Spawn a controlled stress-ng workload (1 CPU + 1 VM worker, 120s timeout)
    SpawnStressor,
    /// Kill any running stress-ng stressor process
    KillStressor,
    /// sync + drop page caches to reduce memory pressure
    DropCaches,
}

/// Whitelisted shell commands the agent may execute
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum ShellCmd {
    CargoCheck,
    CargoTest,
    RustFmt { path: PathBuf },
    ListDataDir,
    ReadTrace,
}

/// Which source file to target for a patch
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum SourceTarget {
    RegulationSelector,
    PatternExtractor,
    SignalBus,
    SelfModelModel,
    Custom(PathBuf),
}

impl SourceTarget {
    pub fn path(&self, src_root: &std::path::Path) -> PathBuf {
        match self {
            SourceTarget::RegulationSelector => src_root.join("regulation/selector.rs"),
            SourceTarget::PatternExtractor   => src_root.join("pattern/extractor.rs"),
            SourceTarget::SignalBus          => src_root.join("signal/bus.rs"),
            SourceTarget::SelfModelModel     => src_root.join("selfmodel/model.rs"),
            SourceTarget::Custom(p)          => p.clone(),
        }
    }
}

/// A primitive action the agent can execute.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Action {
    pub id: u32,
    /// Predicted signal deltas this action will apply (may be empty for pure system ops)
    pub effect_profile: HashMap<SignalId, f64>,
    /// How many ticks this action's effects persist (1 = instant)
    pub duration_ticks: u32,
    /// Metabolic cost — applied as a negative delta to a resource signal
    pub cost: f64,
    /// Optional system operation — if present, executed after signal effects
    pub system_op: Option<SystemOp>,
    /// Minimum continuity level required to execute system_op (0.0 = always)
    pub continuity_gate: f64,
    /// Human-readable label written by the agent itself (None = never labeled)
    pub label: Option<String>,
}

impl Action {
    pub fn new(id: u32, effects: Vec<(SignalId, f64)>, duration_ticks: u32, cost: f64) -> Self {
        Self {
            id,
            effect_profile: effects.into_iter().collect(),
            duration_ticks,
            cost,
            system_op: None,
            continuity_gate: 0.0,
            label: None,
        }
    }

    pub fn with_system_op(mut self, op: SystemOp, continuity_gate: f64) -> Self {
        self.system_op = Some(op);
        self.continuity_gate = continuity_gate;
        self
    }

    pub fn is_system_action(&self) -> bool {
        self.system_op.is_some()
    }
}

/// Registry of all available actions. Supports hot-reload from actions.json.
pub struct ActionSpace {
    actions: Vec<Action>,
    pub next_id: u32,
}

impl ActionSpace {
    pub fn new(actions: Vec<Action>) -> Self {
        let next_id = actions.iter().map(|a| a.id + 1).max().unwrap_or(0);
        Self { actions, next_id }
    }

    pub fn all(&self) -> &[Action] {
        &self.actions
    }

    pub fn get(&self, id: u32) -> Option<&Action> {
        self.actions.iter().find(|a| a.id == id)
    }

    pub fn get_mut(&mut self, id: u32) -> Option<&mut Action> {
        self.actions.iter_mut().find(|a| a.id == id)
    }

    pub fn update_effect(&mut self, action_id: u32, signal_id: SignalId, new_delta: f64) {
        if let Some(a) = self.get_mut(action_id) {
            a.effect_profile.insert(signal_id, new_delta);
        }
    }

    /// Add a new action (e.g. generated by CodeGenerator)
    pub fn add(&mut self, mut action: Action) -> u32 {
        action.id = self.next_id;
        self.next_id += 1;
        let id = action.id;
        tracing::info!("action space: added action {} (system={})", id, action.is_system_action());
        self.actions.push(action);
        id
    }

    /// Remove an action by id
    pub fn remove(&mut self, id: u32) {
        self.actions.retain(|a| a.id != id);
    }

    /// Serialize to JSON for persistence and hot-reload
    pub fn to_json(&self) -> anyhow::Result<String> {
        Ok(serde_json::to_string_pretty(&self.actions)?)
    }

    /// Merge actions from JSON — adds new ids, skips existing
    pub fn merge_from_json(&mut self, json: &str) -> anyhow::Result<usize> {
        let incoming: Vec<Action> = serde_json::from_str(json)?;
        let existing_ids: std::collections::HashSet<u32> = self.actions.iter().map(|a| a.id).collect();
        let mut added = 0;
        for action in incoming {
            if !existing_ids.contains(&action.id) {
                if action.id >= self.next_id {
                    self.next_id = action.id + 1;
                }
                self.actions.push(action);
                added += 1;
            }
        }
        Ok(added)
    }

    pub fn label_action(&mut self, id: u32, label: String) {
        if let Some(a) = self.get_mut(id) {
            a.label = Some(label);
        }
    }
}
